/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MetadataGroup,
} from './MetadataGroup';

export namespace Components {
  interface UvInfoPanel {
    'manifest': string;
    'metadataGroups': MetadataGroup[];
    'showAllLanguages': boolean;
  }
  interface UvMetadataGroup {
    'metadata': MetadataGroup;
  }
}

declare global {


  interface HTMLUvInfoPanelElement extends Components.UvInfoPanel, HTMLStencilElement {}
  var HTMLUvInfoPanelElement: {
    prototype: HTMLUvInfoPanelElement;
    new (): HTMLUvInfoPanelElement;
  };

  interface HTMLUvMetadataGroupElement extends Components.UvMetadataGroup, HTMLStencilElement {}
  var HTMLUvMetadataGroupElement: {
    prototype: HTMLUvMetadataGroupElement;
    new (): HTMLUvMetadataGroupElement;
  };
  interface HTMLElementTagNameMap {
    'uv-info-panel': HTMLUvInfoPanelElement;
    'uv-metadata-group': HTMLUvMetadataGroupElement;
  }
}

declare namespace LocalJSX {
  interface UvInfoPanel extends JSXBase.HTMLAttributes<HTMLUvInfoPanelElement> {
    'manifest'?: string;
    'metadataGroups'?: MetadataGroup[];
    'showAllLanguages'?: boolean;
  }
  interface UvMetadataGroup extends JSXBase.HTMLAttributes<HTMLUvMetadataGroupElement> {
    'metadata'?: MetadataGroup;
  }

  interface IntrinsicElements {
    'uv-info-panel': UvInfoPanel;
    'uv-metadata-group': UvMetadataGroup;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


