/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UvInfoPanel {
    /**
    * The IIIF manifest
    */
    'manifest': string;
  }
}

declare global {


  interface HTMLUvInfoPanelElement extends Components.UvInfoPanel, HTMLStencilElement {}
  var HTMLUvInfoPanelElement: {
    prototype: HTMLUvInfoPanelElement;
    new (): HTMLUvInfoPanelElement;
  };
  interface HTMLElementTagNameMap {
    'uv-info-panel': HTMLUvInfoPanelElement;
  }
}

declare namespace LocalJSX {
  interface UvInfoPanel extends JSXBase.HTMLAttributes<HTMLUvInfoPanelElement> {
    /**
    * The IIIF manifest
    */
    'manifest'?: string;
  }

  interface IntrinsicElements {
    'uv-info-panel': UvInfoPanel;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


